language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ateletin/docker-training -f Dockerfile.dev .

script:
  - docker run -e CI=true ateletin/docker-training npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-training"
  env: "DockerTraining-env"
  bucket_name: "elasticbeanstalk-us-east-2-102536019043"
  bbucket_path: "docker-training"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
