language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ateletin/docker-training -f Dockerfile.dev .

script:
  - docker run -e CI=true ateletin/docker-training npm run test
